### ISSUE TITLE
Karpenter blueprint upgrade to 0.33.1

### ISSUE THREAD

**Issue by vara-bonthu** [awslabs/data-on-eks#408]
```[tasklist]
### Tasks
- [ ] https://github.com/awslabs/data-on-eks/issues/409
- [ ] https://github.com/awslabs/data-on-eks/issues/410
- [ ] https://github.com/awslabs/data-on-eks/issues/411
- [ ] https://github.com/awslabs/data-on-eks/issues/412
- [ ] https://github.com/awslabs/data-on-eks/issues/413
- [ ] https://github.com/awslabs/data-on-eks/issues/414
- [ ] https://github.com/awslabs/data-on-eks/issues/415
- [ ] https://github.com/awslabs/data-on-eks/issues/416
- [ ] https://github.com/awslabs/data-on-eks/issues/417
- [ ] https://github.com/awslabs/data-on-eks/issues/418
- [ ] https://github.com/awslabs/data-on-eks/issues/419
```
